name: Python Library Test

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test-job:
    runs-on: self-hosted 

    steps:
      - name: 📥 1. 깃허브에서 내 코드(hello.py) 다운로드
        uses: actions/checkout@v3

      - name: 📦 2. 파이썬 외부 라이브러리 설치
        run: pip3 install pyfiglet --user

      - name: 🚀 3. 파이썬 스크립트 실행
        run: python3 hello.py
